CREATE TABLE `Users` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `FirstName` VARCHAR(100) NOT NULL,
    `LastName` VARCHAR(100) NOT NULL,
    `Login` VARCHAR(100) NOT NULL UNIQUE,
    `Password` CHAR(60) NOT NULL, -- bcrypt hash
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB;

CREATE TABLE `Contacts` (
    `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `UserID` INT UNSIGNED NOT NULL,
    `FirstName` VARCHAR(100) NOT NULL,
    `LastName` VARCHAR(100) NOT NULL,
    `Phone` VARCHAR(20) NOT NULL,
    `Email` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`),
    FOREIGN KEY (`UserID`) REFERENCES `Users`(`ID`) ON DELETE CASCADE

    `LastModified` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
) ENGINE=InnoDB;
